// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiy2ci_nYSiCpJux-kWOO9giIyPpVuptA',
    appId: '1:744989929665:web:19226d00a469b6a6866440',
    messagingSenderId: '744989929665',
    projectId: 'kidspalace-b8967',
    authDomain: 'kidspalace-b8967.firebaseapp.com',
    storageBucket: 'kidspalace-b8967.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr8zyZVfFEQJFZ6HK2pargD3HBfzJGJi8',
    appId: '1:744989929665:android:27b6105a43b15f44866440',
    messagingSenderId: '744989929665',
    projectId: 'kidspalace-b8967',
    storageBucket: 'kidspalace-b8967.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgHaCkHHxqo-nQdoBMOmLktr4BgoLyXiU',
    appId: '1:744989929665:ios:f1d998480a49d4ed866440',
    messagingSenderId: '744989929665',
    projectId: 'kidspalace-b8967',
    storageBucket: 'kidspalace-b8967.appspot.com',
    iosClientId: '744989929665-1l04hgqg8mqv8m8hb23id1hd9rt2vcjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.kids',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgHaCkHHxqo-nQdoBMOmLktr4BgoLyXiU',
    appId: '1:744989929665:ios:f1d998480a49d4ed866440',
    messagingSenderId: '744989929665',
    projectId: 'kidspalace-b8967',
    storageBucket: 'kidspalace-b8967.appspot.com',
    iosClientId: '744989929665-1l04hgqg8mqv8m8hb23id1hd9rt2vcjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.kids',
  );
}
